server:
  port: 8082
  servlet:
    context-path: /api

spring:
  output:
    ansi:
      enabled: always
  application:
    name: bank-pagos-clientes-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.56.101:3306/DB_LOCAL?createDatabaseIfNotExist=true&useSSL=false
    username: server
    password: admin123
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      connection-test-query: select 1;
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.format_sql: false
